name: Python Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: コード取得
        uses: actions/checkout@v4

      - name: Pythonセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: pytestインストール
        run: pip install pytest

      - name: テスト実行
        run: pytest