"""add status to items

Revision ID: f8086a84c6ff
Revises: 7ccb050e23e2
Create Date: 2026-07-31 14:37:34.910865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8086a84c6ff'
down_revision: Union[str, Sequence[str], None] = '7ccb050e23e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('status', sa.String(), server_default='active', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'status')
    # ### end Alembic commands ###
