name: Python Test

# push または Pull Request時に実行
on:
  push:
  pull_request:

jobs:
  test:

    # GitHubが用意するUbuntu環境で実行
    runs-on: ubuntu-latest

    steps:

      # ソースコードを取得
      - name: Checkout
        uses: actions/checkout@v4

      # Docker Composeのイメージをビルド
      # DockerfileからFastAPIコンテナを作成
      - name: Build containers
        run: docker compose build

      # FastAPI + PostgreSQL を起動
      #
      # app:
      #   FastAPIコンテナ
      #
      # db:
      #   PostgreSQLコンテナ
      #
      # -d はバックグラウンド実行
      - name: Start containers
        run: docker compose up -d

      # FastAPI/PostgreSQL起動待ち
      #
      # 起動直後はDB接続できない場合があるため
      # 少し待つ
      - name: Wait for API
        run: sleep 10

      # Ruffによる静的解析
      #
      # appコンテナ内で実行
      #
      # -T はGitHub Actions用
      # 擬似端末(TTY)を割り当てない
      - name: Run lint
        run: docker compose exec -T app ruff check .

      # pytest実行
      #
      # PostgreSQLへ接続するため
      # appコンテナ内で実行
      - name: Run tests
        run: docker compose exec -T app pytest -v

      # GET /
      #
      # API起動確認
      - name: Validate API response
        run: |
          response=$(curl -s http://localhost:8000)
          echo "$response"
          test "$response" = '{"message":"Hello Docker FastAPI"}'

      # GET /hello/{name}
      #
      # Path Parameter確認
      - name: Validate dynamic API response
        run: |
          response=$(curl -s http://localhost:8000/hello/Taro)
          echo "$response"
          test "$response" = '{"message":"Hello Taro"}'

      # POST /echo
      #
      # JSON送信確認
      - name: Validate POST API response
        run: |
          response=$(curl -s -X POST http://localhost:8000/echo \
            -H "Content-Type: application/json" \
            -d '{"name":"Taro"}')

          echo "$response"

          test "$response" = '{"message":"Hello Taro"}'

      # 後片付け
      #
      # always() により
      # テスト失敗時も必ず実行
      #
      # -v は Volume削除
      # PostgreSQLデータも削除される
      - name: Stop containers
        if: always()
        run: docker compose down -v